---
- name: Downloading and enable the EPEL repository definitions.
  action: command rpm -Uvh --replacepkgs https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: Install Docker
  yum: pkg=docker-io state=present

- name: Start service
  service: name=docker state=started

- name: Add --dns arguments
  lineinfile: dest=/etc/sysconfig/docker state=present regexp="^OPTIONS=" line="OPTIONS=\"--selinux-enabled --log-driver=journald --dns 85.25.255.10 --dns 85.25.128.10\""
  notify:
    - restart docker
