---
#- name: Downloading and enable the EPEL repository definitions.
#  action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
- name: Downloading and enable the EPEL repository definitions.
  yum: name={{ epel_repo }} state=present

- name: Install Docker
  yum: pkg=docker-io state=present

- name: Start service
  service: name=docker state=started
